# Automatically build and test HeardIT back-end on push and pull-request
# using GitHub Actions.

name: HeardIT Frontend CICD

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    IMAGE_NAME: jumorto/hearditfrontend-image:latest

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install
            - name: Allow build permissions
              run: chmod +x node_modules/.bin/react-scripts
            - name: Build
              run: npm run build

            - name: Test
              run: npm test
